name: localdaily
description: LocalDaily App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  fluro: 2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Configure
  built_value: ^8.1.3
  connectivity: ^3.0.6
  get_it: ^7.2.0
  lint: ^1.7.2
  rxdart: ^0.27.2
  provider: ^6.0.1
  json_annotation: ^4.4.0
  retrofit: ^2.0.1
  dio: ^4.0.1
  url_launcher: ^6.0.20
  uni_links: ^0.5.1
  shared_preferences: ^2.0.6

  #Assets
  cupertino_icons: ^1.0.3
  flutter_svg: ^0.23.0+1
  crypto: ^3.0.1
  double_back_to_close_app: ^2.0.1
  flutter_toggle_tab: ^1.1.7
  string_validator: ^0.3.0
  flutter_datetime_picker: ^1.5.1
  open_mail_app: ^0.4.1
  pin_code_fields: ^7.3.0
  checkbox_formfield: ^0.2.0
  sha3: ^0.2.0
  hex: ^0.2.0
  bip32: ^2.0.0
  web3dart: ^2.3.5
  bip39: ^1.0.6
  flutter_launcher_icons: ^0.9.2

  #Widgets
  shimmer: ^2.0.0
  eth_sig_util: ^0.0.7
  font_awesome_flutter: ^10.1.0
  country_code_picker: ^2.0.2
  dotted_line: ^3.1.0
  image_picker: ^0.8.5
  permission_handler: ^9.2.0
  flutter_slidable: ^1.2.0
  flutter_rating_bar: ^4.0.0
  path_provider: ^2.0.9
  file_picker: ^4.5.1
  intl: ^0.17.0
  open_file: ^3.2.1

dev_dependencies:
  build_runner: ^2.1.4
  built_value_generator: ^8.1.3
  json_serializable: ^6.0.1
  retrofit_generator: ^2.0.1+2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/ICONAPP.png"

flutter:
  uses-material-design: true
#  generate: true
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/json/

  fonts:
    - family: GTWalsheimPro
      fonts:
        - asset: lib/assets/fonts/GTWalsheimPro-Bold.ttf
        - asset: lib/assets/fonts/GTWalsheimPro-Black.ttf
        - asset: lib/assets/fonts/GTWalsheimPro-Regular.ttf
        - asset: lib/assets/fonts/GTWalsheimPro-RegularOblique.ttf
