name: bogota_app
description: Bogotá DC travel

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Configure Structure
  provider: ^5.0.0
  json_annotation: ^4.0.0
  http: ^0.13.0
  get_it: ^6.0.0
  rxdart: ^0.26.0
  build_runner_core: ^6.1.12
  intl: ^0.17.0

  #Assets
  flutter_svg: ^0.21.0-nullsafety.0
  video_player: ^2.1.1
  just_audio: ^0.7.0

  #Views
  url_launcher: ^6.0.2
  flutter_rating_bar: ^4.0.0
  flutter_switch: ^0.3.0-nullsafety.0
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  share: ^2.0.1
  country_state_city_picker: ^1.2.7
  unique_ids: ^2.0.0
  location: ^4.1.1
  hive: ^2.0.4
  hive_generator: ^1.1.0
  app_settings: ^4.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.5
  json_serializable: ^4.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - lib/commons/

  fonts:
    - family: IdtIcons
      fonts:
        - asset: lib/assets/icons/IdtIcons.ttf

    - family: MuseoSans
      fonts:
        - asset: lib/assets/fonts/MuseoSans-100.ttf
        - asset: lib/assets/fonts/MuseoSans-500.ttf
        - asset: lib/assets/fonts/MuseoSans-700.ttf
        - asset: lib/assets/fonts/MuseoSans-900.ttf
        - asset: lib/assets/fonts/MyriadPro-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

